account_sid = st.secrets["ACed69b33546757121abd0fe5d9f9455b5"]
    auth_token = st.secrets["854aac2c8b57dbf945babd600c885bf8"]
    from_whatsapp = st.secrets["whatsapp:+14155238886"]  # e.g., 'whatsapp:+14155238886'
    to_whatsapp = st.secrets["whatsapp:+966544221519"]      # e.g., 'whatsapp:+911234567890'

