TWILIO_ACCOUNT_SID = "ACed69b33546757121abd0fe5d9f9455b5"
TWILIO_AUTH_TOKEN = "854aac2c8b57dbf945babd600c885bf8"
TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"
MY_WHATSAPP_NUMBER = "whatsapp:+966544221519" # Wo number jispar message chahiye
